---
title: "Home"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

#### **Overview**  
Welcome to my course on computational tools for language researchers. The development of the resources on this site is in progress, and will continue to grow over time. If you are here, I imagine that you are (a) interested in language, (b) have some basic computer skills, and (c) want to be able to analyze some aspect(s) of language using your computer. If (a)-(c) fit you, then you are probably in the right place. For example, maybe you are interested in collecting and/or analyzing text data and studying those texts for patterns of usage. Likewise, maybe you want to be able to study the features associated with phonological information present in speech, and would like to be able to analyze and visualize that information to understand it better.  
  
  It follows from (b) that you understand some basics about how your computer works, and the quantitative tools that can be used on it. This hopefully includes some previous work with data in tabular form, even if just in Microsoft Excel. This course primarily uses [R](https://www.r-project.org) as a computational resource, and [RStudio](https://www.rstudio.com) as the environment in which R is used. Experience with these computational resources is not required for this course, though will no doubt make it easier for you to be successful.
  
#### **What is this course about?**  
This course is about using your computer to organize, develop, and analyze your language data. Indeed, many of the tools here are not uniquely useful to language research, though language data is the common theme throughout all the activities contained in these pages. Relatedly, this course is focused on quantitative methods. All this means is that the focus of this course is on aspects of language that can be organized with respect to their quantifiable properties. This doesn't mean that the focus is on frequentist statistics, or any particular statistical method. Rather, I would like to teach you about what you can do with language when you look at it through the lens of quantification. Nonetheless, description is a facet of this enterprise, and description is always a part of the process of quantifying a domain of human psychology (indeed we quantify in order to describe). This course is on the quantification part, as a necessary (but not sufficient) aspect of describing language in its many levels and forms.  
  So, this course is about organizing and seeing language data in a quantifiable form. This will involve language data that I find most exciting, including aggregating and analyzing text corpora and looking at the semantic, orthographic, and phonological features that are important to understanding reading behavior and development. Nonetheless, we will also cover basics about data reading, writing and cleaning that will facilitate working with your language data in a tidy and organized fashion.
  
#### **Who is this course for?**  
This course is designed for beginners in language science and data analysis for language science. As a result, the resources and skills covered in the course are suitable for undergraduates and graduate students who want to get a start in developing skills along these lines, but will cover more sophisticated skills that will hopefully serve as a gateway to advanced methods of analysis. In order to do well in this class you need to know what language is and how it might be quantified for analysis. Experience in R or some other statistical computing software is not required but will be very beneficial.  

  
#### **Course goals**  
Someone who takes this course will develop the ability to... 

1. Read, write, and clean data, especially language data, in useful formats for analysis and storage
2. Understand and use statistical computing in R
3. Write functions to process data
4. Visualize data for descriptive and reporting purposes
5. Perform natural language processing tasks of various kinds
6. Do basic tasks using regular expressions
7. Write documents in R that describe and analyze data with an eye towards communicating your work to others
  
***